---
# tasks file for setup-frontend

- name: Pull frontend Docker image
  docker_image:
    name: allankimutai/client:v1.0.0
    source: pull
  become: yes

- name: Run frontend container
  docker_container:
    name: frontend
    image: allankimutai/client:v1.0.0
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
  become: yes
