version: '3.9'


services:
 backend:
   build:
     context: ./backend
     dockerfile: Dockerfile
     args:
      - VERSION=v1.0.0
   image: allankimutai/backend:v1.0.0
   ports:
     - "5000:5000"
   volumes:
     - type: volume
       source: backend-data
       target: /app/backend
   environment:
     - MONGODB_URI=mongodb://mongo:27017/yolo
   depends_on:
     - mongo
   networks:
     - yolo-network


 client: 
   build:
     context: ./client
     dockerfile: Dockerfile
     args:
     - VERSION=v1.0.0
   image: allankimutai/client:v1.0.0
   ports:
     - "3000:3000"
   volumes:
     - type: volume
       source: client-data
       target: /app/client 
   depends_on:
     - backend
   networks:
     - yolo-network


 mongo:
   image: mongo
   ports:
     - "27017:27017"
   volumes:
     - type: volume
       source: mongo-data
       target: /data/db
   networks:
     - yolo-network


networks:
 yolo-network:
   driver: bridge


volumes:
 backend-data:
   driver: local
 client-data:
   driver: local
 mongo-data:
   driver: local
