---
# tasks file for setup-backend

- name: Pull backend Docker image
  docker_image:
    name: allankimutai/backend:v1.0.0
    source: pull
  become: yes

- name: Run backend container
  docker_container:
    name: backend
    image: allankimutai/backend:v1.0.0
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
  become: yes
