---
# tasks file for setup-mongo-db
- name: Create Docker network
  community.docker.docker_network:
    name: yolo-network
    state: present

- name: Run MongoDB Docker container
  docker_container:
    name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    networks:
      - name: yolo-network
  become: yes
