apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/YOUR_PROJECT_ID/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/yolo"
